---
- name: install node and npm
  hosts: 13.234.37.93
  tasks:
    - name: update repo and cache
      ansible.builtin.dnf:
         name:
          - nodejs
          - npm

- name: create new linux user          

- name: Deploy nodejs app
  hosts: 13.234.37.93
  tasks:
    - name: unpack tar file
      unarchive: 
        src: /mnt/c/Users/Janitha/Desktop/Projects/deploy website using ansible/project-19/New folder/output.tar
        dest: /root/
    - name: Build Next.js app
      command: npm run build
      args:
        chdir: /root/app
    - name: Start Next.js app in background
      ansible.builtin.command: npm start -- --hostname 0.0.0.0 --port 3000
      args:
        chdir: /root/app
      async: 60
      poll: 0
    - name: ensure app is runing
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status}}


      