---
 - name: create nginx web server
   hosts: aws #also can add ip address of server
   tasks: 
   - name: install nginx server
     yum:
      name: nginx
      state: latest #we can stop this service using latest-> absent and started->stopped
   - name: starts nginx server
     service: 
      name: nginx
      state: started
