---
 - name: create nginx web server
   hosts: aws #also can add ip address of server
   tasks: 
   - name: install nginx server
     yum:
      name: nginx
      state: latest
   - name: starts nginx server
     service: 
      name: nginx
      state: started
